BIS/BIS/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

BIS/attributes/models.py
from django.db import models
from django.db.models import JSONField
from core.models import User
from buildings.models import Building
# Create your models here.
class Attribute(models.Model):
    TYPE_CHOICES=[
        ('static', 'Static'),
        ('dynamic', 'Dynamic'),
    ]
    shortname = models.CharField()
    type = models.CharField(max_length=7, choices=TYPE_CHOICES, null=True, blank=True)
    inserted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='+')
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='+')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)
    deleted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='+')
    if(type == 'static'):
        def __str__(self):
            return f'{self.shortname}'
    else:
        
        def __str__(self):
            return f'{self.shortname}'

class BuildingAttribute(models.Model):
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    value = models.CharField(max_length=255, blank=True, null=True)  # Nullable value
    inserted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='+')
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='+')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.building.shortname} - {self.attribute.shortname}'

class AttributeHistory(models.Model):
    building_attribute = models.ForeignKey(BuildingAttribute, on_delete=models.CASCADE)
    previous_value = models.CharField(max_length=255, blank=True, null=True)  # For static attributes
    new_value = models.CharField(max_length=255, blank=True, null=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'History of {self.building_attribute}'

class Property(models.Model):
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    data = models.JSONField(null=True, blank=True)  # Nullable JSON data
    inserted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='+')
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='+')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)
    deleted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='+')

    def __str__(self):
        return f'{self.building.shortname} - {self.attribute.shortname}'
    
class PropertyHistory(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    previous_data = JSONField(blank=True, null=True)
    new_data = JSONField(blank=True, null=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'History of {self.property}'

BIS/attributes/forms.py
from django import forms
from .models import Attribute, Property, BuildingAttribute
import json

class AttributeForms(forms.ModelForm):
    class Meta:
        model = Attribute
        exclude = ['inserted_by', 'updated_by', 'deleted_by', 'is_deleted' ]
        #fields = '__all__'

class PropertyForms(forms.ModelForm):
    class Meta:
        model = Property
        exclude = ['data', 'updated_by', 'inserted_by', 'is_deleted', 'deleted_by']
    
    def __init__(self, *args, **kwargs):
        super(PropertyForms, self).__init__(*args, **kwargs)
        
        self.fields['attribute'].queryset = Attribute.objects.filter(type='dynamic')
        
class BuildingAttributeForms(forms.ModelForm):
    class Meta:
        model = BuildingAttribute
        exclude = ['attribute', 'inserted_by', 'updated_by', 'is_deleted', 'deleted_by']

BIS/attributes/views.py
from django.shortcuts import render
from attributes.models import Attribute, Property, BuildingAttribute
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from .forms import AttributeForms, PropertyForms, BuildingAttributeForms
from django.urls import reverse
from django.db.models import Max
import json
# Create your views here.
def get_attribute(request, attribute_id):
    try:
        attribute = Attribute.objects.get(id=attribute_id)
        properties = Property.objects.filter(attribute=attribute)
        property_data = {}
        
        if properties.exists():
            property_instance = properties.first()
            property_data = property_instance.data
        
        attribute_data = {
            'id': attribute.id,
            'shortname': attribute.shortname,
            'type': attribute.type,
            'properties': property_data
        }
        return JsonResponse(attribute_data, safe=False)
    except Attribute.DoesNotExist:
        return JsonResponse({'error': 'Attribute not found'}, status=404)
    
def get_property(request, property_id):
    try:
        property = Property.objects.get(id=property_id)
        property_data = {
            'id': property.id,
            'data': property.data,
        }
        return JsonResponse(property_data, safe=False)
    except Property.DoesNotExist:
        return JsonResponse({'error': 'Property not found'}, status=404)

def add_attribute(request):
    if request.method == "POST":
        form = AttributeForms(request.POST)
        form_b = BuildingAttributeForms(request.POST)
        
        if form.is_valid() and form_b.is_valid():
            attribute = form.save(commit=False)
            buildingattribute = form_b.save(commit=False)
            
            attribute.inserted_by = request.user
            attribute.is_deleted = False
            attribute.save()
            
            buildingattribute.attribute = attribute
            buildingattribute.inserted_by = request.user
            buildingattribute.is_deleted = False
            buildingattribute.save()
            
            return HttpResponseRedirect(reverse('sysadmin'))
        else:
            return render(request, 'attribute/addAttribute.html', {
                'addAttributesForm': form,
                'addBuildingAttributeForm': form_b,
                'errors': form.errors
            })
    
    else:
        form = AttributeForms()
        form_b = BuildingAttributeForms()
        
    return render(request, 'attribute/addAttribute.html', {
        'addAttributesForm': form,
        'addBuildingAttributeForm': form_b
    })
def add_property(request):
    addPropertiesForm = PropertyForms()
    
    if request.method == "POST":
        form = PropertyForms(request.POST)
        if form.is_valid():
            property_instance = form.save(commit=False)
            
            new_keys = request.POST.getlist('new_keys[]')
            new_values = request.POST.getlist('new_values[]')
            data = {}
            if new_keys:
                for i, key in enumerate(new_keys):
                    value = new_values[i] if i < len(new_values) else None
                    data[key] = value
                property_instance.data = data
            property_instance.inserted_by = request.user
            property_instance.save()
            return HttpResponseRedirect(reverse('sysadmin'))
        else:
            return render(request, 'property/addProperty.html', {'addPropertiesForm': form, 'errors': form.errors})
        
    attribute_id = request.GET.get('attribute')
    existing_data = {}

    if attribute_id:
        try:
            attribute = Attribute.objects.get(id=attribute_id)
            properties = Property.objects.filter(attribute=attribute).first()
            if properties:
                existing_data = properties.data
        except Attribute.DoesNotExist:
            pass
    
    return render(request, 'property/addProperty.html', {
        'addPropertiesForm': addPropertiesForm,
        'existing_data': json.dumps(existing_data)
    })
from django.shortcuts import get_object_or_404

def edit_attribute(request, attribute_id):
    attribute = get_object_or_404(Attribute, id=attribute_id)
    if request.method == 'POST':
        form = AttributeForms(request.POST, instance=attribute)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('sysadmin'))
    else:
        form = AttributeForms(instance=attribute)
    
    return render(request, 'attribute/editAttribute.html', {
        'addAttributesForm': form
    })

def edit_property(request, property_id):
    property_instance = get_object_or_404(Property, id=property_id)
    if request.method == 'POST':
        form = PropertyForms(request.POST, instance=property_instance)
        if form.is_valid():
            new_keys = request.POST.getlist('new_keys[]')
            new_values = request.POST.getlist('new_values[]')
            data = {}
            if new_keys:
                for i, key in enumerate(new_keys):
                    value = new_values[i] if i < len(new_values) else None
                    data[key] = value
                property_instance.data = data
            
            form.save()
            return HttpResponseRedirect(reverse('sysadmin'))
    else:
        form = PropertyForms(instance=property_instance)
    
    return render(request, 'property/editProperty.html', {
        'addPropertiesForm': form,
        'existing_data': json.dumps(property_instance.data)
    })

def delete_attribute(request, attribute_id):
    attribute = get_object_or_404(Attribute, id=attribute_id)
    attribute.is_deleted = True
    attribute.deleted_by = request.user
    attribute.save()
    return HttpResponseRedirect(reverse('sysadmin'))

def delete_property(request, property_id):
    property_instance = get_object_or_404(Property, id=property_id)
    property_instance.is_deleted = True
    property_instance.deleted_by = request.user
    property_instance.save()
    return HttpResponseRedirect(reverse('sysadmin'))

def recover_attribute(request, attribute_id):
    attribute = get_object_or_404(Attribute, id=attribute_id)
    attribute.is_deleted = False
    attribute.deleted_by = None
    attribute.save()
    return HttpResponseRedirect(reverse('sysadmin'))

def recover_property(request, property_id):
    property_instance = get_object_or_404(Property, id=property_id)
    property_instance.is_deleted = False
    property_instance.deleted_by = None
    property_instance.save()
    return HttpResponseRedirect(reverse('sysadmin'))

BIS/attributes/templates/property/addProperty.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Property</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/property.css' %}">
</head>
<body>
    <nav class="navbar">
        <ul class="left-menu">
            <li><a href="{% url 'sysadmin' %}">Home</a></li>
            {% if user.role_id == 3 %}
                <li><a href="#">About</a></li>
            {% elif user.role_id == 2 %}
                <li><a href="{% url 'generate_building_report' %}">Generate Report</a></li>
            {% else %}
            {% endif %}
        </ul>       
        <ul class="right-menu">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle">{{ request.user.first_name }} [{{request.user.role}}]</a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'sign_out' %}">Sign out</a></li>
                </ul>
            </li>
        </ul>
    </nav>

    <div class="cover">
        <div class="form-container">
            <h2>Add Property</h2>
            <form action="" method="POST">
                {% csrf_token %}
        
                {{ addPropertiesForm.as_p }}
        
                <div id="dynamic-keys">
                    <h3>Dynamic Keys</h3>
                </div>
                
                <button type="button" id="add-key-button">Add Key</button>
        
                <br><br>
                <input type="submit" value="Add Property">
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            function loadAttributes(buildingId) {
                $.ajax({
                    url: `/api/building/${buildingId}`,
                    method: 'GET', 
                    success: function(response) {
                        var attributes = response.attributes;
                        var $attributeSelect = $('#id_attribute');
                        $attributeSelect.empty(); 
                        
                        $.each(attributes, function(index, attribute) {
                            if (attribute['attribute__type'] === 'dynamic') {
                            
                                var option = new Option(attribute['attribute__shortname'], attribute['attribute__id']);
                                $attributeSelect.append(option);
                            }
                        });

                        $attributeSelect.trigger('change');
                    },
                    error: function(xhr, status, error) {
                        console.error('Error fetching attributes:', status, error);
                    }
                });
            }

    
            function loadKeyOptions(attributeId) {
                $.ajax({
                    url: `/api/attribute/${attributeId}`,
                    success: function(response) {
                        var properties = response.properties;
                        $('#dynamic-keys').empty();
                        $.each(properties, function(key, value) {
                            addKey(key, value);
                        });
                    }
                });
            }
    
            function newKey(key = '', value = '') {
                var $container = $('#dynamic-keys');
                var $newDiv = $('<div>').addClass('key-value-pair');
    
                var $keyInput = $('<input>')
                    .attr('type', 'text')
                    .attr('name', 'new_keys[]')
                    .val(key)
                    .attr('readonly', false);
                $newDiv.append($keyInput);
    
                var $valueInput = $('<input>')
                    .attr('type', 'text')
                    .attr('name', 'new_values[]')
                    .val(value);
                $newDiv.append($valueInput);
    
                var $removeButton = $('<button>')
                    .attr('type', 'button')
                    .text('Remove')
                    .on('click', function() {
                        $newDiv.remove();
                    });
                $newDiv.append($removeButton);
    
                $container.append($newDiv);
            }
    
            function addKey(key = '', value = '') {
                var $container = $('#dynamic-keys');
                var $newDiv = $('<div>').addClass('key-value-pair');
    
                var $keyInput = $('<input>')
                    .attr('type', 'text')
                    .attr('name', 'new_keys[]')
                    .val(key)
                    .attr('readonly', true);
                $newDiv.append($keyInput);
    
                var $valueInput = $('<input>')
                    .attr('type', 'text')
                    .attr('name', 'new_values[]')
                    .val(value);
                $newDiv.append($valueInput);
    
                var $removeButton = $('<button>')
                    .attr('type', 'button')
                    .text('Remove')
                    .on('click', function() {
                        $newDiv.remove();
                    });
                $newDiv.append($removeButton);
    
                $container.append($newDiv);
            }

            $('#id_building').on('change', function() {
                var buildingId = $(this).val();
                if (buildingId) {
                    loadAttributes(buildingId);
                }
            });

            $('#id_attribute').on('change', function() {
                var attributeId = $(this).val();
                if (attributeId) {
                    loadKeyOptions(attributeId);
                }
            });

            $('#add-key-button').on('click', function() {
                newKey();
            });

            var initialBuildingId = $('#id_building').val();
            if (initialBuildingId) {
                loadAttributes(initialBuildingId);
            }
        });
    </script>
</body>
</html>

BIS/attributes/templates/property/editProperty.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Property</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/property.css' %}">
</head>
<body>
    <nav class="navbar">
        <ul class="left-menu">
            <li><a href="{% url 'sysadmin' %}">Home</a></li>
            {% if user.role_id == 3 %}
                <li><a href="#">About</a></li>
            {% elif user.role_id == 2 %}
                <li><a href="{% url 'generate_building_report' %}">Generate Report</a></li>
            {% else %}
            {% endif %}
        </ul>       
        <ul class="right-menu">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle">{{ request.user.first_name }} [{{request.user.role}}]</a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'sign_out' %}">Sign out</a></li>
                </ul>
            </li>
        </ul>
    </nav>

    <div class="cover">
        <div class="form-container">
            <h2>Edit Property</h2>
            <form action="" method="POST">
                {% csrf_token %}
        
                {{ addPropertiesForm.as_p }}
        
                <div id="dynamic-keys">
                    <h3>Dynamic Keys</h3>
                </div>
                
                <button type="button" id="add-key-button">Add Key</button>
        
                <br><br>
                <input type="submit" value="Add Property">
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            function loadAttributes(buildingId) {
                $.ajax({
                    url: `/api/building/${buildingId}`,
                    method: 'GET',
                    success: function(response) {
                        var attributes = response.attributes;
                        var $attributeSelect = $('#id_attribute');
                        $attributeSelect.empty();
                        
                        $.each(attributes, function(index, attribute) {
                            if (attribute['attribute__type'] === 'dynamic') {
                                var option = new Option(attribute['attribute__shortname'], attribute['attribute__id']);
                                $attributeSelect.append(option);
                            }
                        });

                        $attributeSelect.trigger('change');
                    },
                    error: function(xhr, status, error) {
                        console.error('Error fetching attributes:', status, error);
                    }
                });
            }

    
            function loadKeyOptions(attributeId) {
                $.ajax({
                    url: `/api/attribute/${attributeId}`,
                    success: function(response) {
                        var properties = response.properties;
                        $('#dynamic-keys').empty();
                        $.each(properties, function(key, value) {
                            addKey(key, value);
                        });
                    }
                });
            }
    
            function newKey(key = '', value = '') {
                var $container = $('#dynamic-keys');
                var $newDiv = $('<div>').addClass('key-value-pair');
    
                var $keyInput = $('<input>')
                    .attr('type', 'text')
                    .attr('name', 'new_keys[]')
                    .val(key)
                    .attr('readonly', false);
                $newDiv.append($keyInput);
    
                var $valueInput = $('<input>')
                    .attr('type', 'text')
                    .attr('name', 'new_values[]')
                    .val(value);
                $newDiv.append($valueInput);
    
                var $removeButton = $('<button>')
                    .attr('type', 'button')
                    .text('Remove')
                    .on('click', function() {
                        $newDiv.remove();
                    });
                $newDiv.append($removeButton);
    
                $container.append($newDiv);
            }
    
            function addKey(key = '', value = '') {
                var $container = $('#dynamic-keys');
                var $newDiv = $('<div>').addClass('key-value-pair');
    
                var $keyInput = $('<input>')
                    .attr('type', 'text')
                    .attr('name', 'new_keys[]')
                    .val(key)
                    .attr('readonly', false);
                $newDiv.append($keyInput);
    
                var $valueInput = $('<input>')
                    .attr('type', 'text')
                    .attr('name', 'new_values[]')
                    .val(value);
                $newDiv.append($valueInput);
    
                var $removeButton = $('<button>')
                    .attr('type', 'button')
                    .text('Remove')
                    .on('click', function() {
                        $newDiv.remove();
                    });
                $newDiv.append($removeButton);
    
                $container.append($newDiv);
            }

            $('#id_building').on('change', function() {
                var buildingId = $(this).val();
                if (buildingId) {
                    loadAttributes(buildingId);
                }
            });
    
            $('#id_attribute').on('change', function() {
                var attributeId = $(this).val();
                if (attributeId) {
                    loadKeyOptions(attributeId);
                }
            });

            $('#add-key-button').on('click', function() {
                newKey();  // Add empty key-value pair
            });

            var initialBuildingId = $('#id_building').val();
            if (initialBuildingId) {
                loadAttributes(initialBuildingId);
            }
        });
    </script>
</body>
</html>